Resources:
  CreateEc2Machines:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0cefa1602ef690491
      KeyName: demba
      InstanceType: t2.micro
      SecurityGroupIds:
        - sg-0b59ccbff3e13d1d3
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: caliph3r
      VersioningConfiguration: Enabled